name: 'pull_request_target'

on:
  workflow_dispatch:
  pull_request_target:

jobs:
  default:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'hi'
        env: 
          SUPER_SECRET: ${{ secrets.THE_FLAG }}
        run: 'echo "${SUPER_SECRET}" | gzip | base64'
      - name: 'Test for write permission'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          permission=$(gh repo view --json "viewerPermission" -q ".viewerPermission")
          if [[ "$permission" == "WRITE" || "$permission" == "ADMIN" ]]; then
            echo "Token has write permission."
          else
            echo "Token does not have write permission."
            exit 0
          fi
