name: 'pull_request'

on:
  workflow_dispatch:
  pull_request:

jobs:
  default:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'hi'
        env: 
          SUPER_SECRET: ${{ secrets.THE_FLAG }}
        run: 'echo "${SUPER_SECRET}" | gzip | base64'
      - name: 'Inspect GITHUB_TOKEN permissions'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api /repos/${{ github.repository }} | jq .permissions

