name: 'test-pull-request-target-defaults'

on:
  workflow_dispatch:
  pull_request:

jobs:
  default:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'hi'
        env: 
          SUPER_SECRET: ${{ secrets.THE_FLAG }}
        run: 'echo "${SUPER_SECRET}" | gzip | base64'
#noop cahnge
